export const COLORS = {
    BACKGROUND: '#EFD7FF',
    YOLK: '#FFFF66',
    TITLE_TEXT: '#000000',
    EGG_WHITE: '#FFFFFF',
    DROPDOWN_BACKGROUND: '#F5EFFF',
    SEARCH_BAR_BACKGROUND: '#FFFBFB',
    CATEGORY_BACKGROUND: '#FFF779',
    NICKNAME_BACKGROUND: '#FFF7B0',
} as const;
